### PR TITLE
Pre-commit

### PR DESCRIPTION
**Pull request by janosh**
Follow up to #1445.

### CODE REVIEW

**Comment by janosh** [comment]
@jay0lee This is ready for review. What better to do on a Sunday. 😄

**Comment by devilshezi0** [comment]
7710711def30d07e31fac8f8d0b88903c242d9ac

**Review by devilshezi0 — APPROVED** [review]

**Comment by devilshezi0** [comment]
e26b95cf31ed4b9459c20031ab29c546f138fd9f

**Comment by devilshezi0** [comment]
> Follow up to #1445.

**Pull request merged**
